openapi: 3.1.0
info:
  version: '1.0'
  title: Vessel-Insights
  summary: Technical documentation for the Pole Star Vessel Insights API
  description: ''
  contact:
    name: support
    url: www.polestarglobal.com/support
    email: support@polestarglobal.com
servers:
  - url: 'https://api.polestar-production.com/vessel-insights/'
    description: Production
paths:
  '/v1/vessel-characteristics/{imo}':
    get:
      tags:
        - Vessel Characteristics
      summary: Vessel Characteristics
      description: Get static vessel information fields for a single vessel. The information returned will be the latest available data.
      operationId: get-v1-vessel-characteristics-imo
      parameters:
        - $ref: '#/components/parameters/imo'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VesselCharacteristicsResponseBody'
              examples:
                OK:
                  $ref: '#/components/examples/vessel_characteristics_200'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error_Response'
              examples:
                IMO Incorrectly Formatted:
                  $ref: '#/components/examples/vessel_characteristics_400'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error_Response'
              examples:
                Unauthorized:
                  $ref: '#/components/examples/vessel_characteristics_401'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error_Response'
              examples:
                Forbidden:
                  $ref: '#/components/examples/vessel_characteristics_403'
        '404':
          description: Resource not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error_Response'
              examples:
                Not Found:
                  $ref: '#/components/examples/vessel_characteristics_404'
        '405':
          description: Method Not Allowed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error_Response'
              examples:
                Method Not Allowed:
                  $ref: '#/components/examples/vessel_characteristics_405'
        '429':
          description: Too Many Requests
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error_Response'
              examples:
                Too Many Requests:
                  $ref: '#/components/examples/vessel_characteristics_429'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error_Response'
              examples:
                Internal Server Error:
                  $ref: '#/components/examples/vessel_characteristics_500'
      security:
        - JWT: []
      servers:
        - url: 'https://api.polestar-production.com/vessel-insights/'
          description: Production
      x-internal: false
components:
  parameters:
    imo:
      name: imo
      in: path
      description: The vessel's IMO number
      required: true
      schema:
        type: integer
        format: int32
        examples:
          - 9169055
  securitySchemes:
    JWT:
      type: http
      scheme: bearer
      bearerFormat: JWT
  examples:
    vessel_characteristics_200:
      value:
        meta:
          request_id: 004ab686-9a00-428c-b907-97812cf923ab
          request_timestamp: '2024-09-24T12:18:01Z'
        data:
          imo: '9169055'
          flag:
            name: Liberia
            country_code: LBR
            effective_date: '2017-11-12'
          mmsi: '636018321'
          name: MSC ADRIANA II
          type: Container (FC)
          draught: 19
          asset_id: ea2eac05-a542-4fc3-869a-d318057e3781
          callsign: D5PE9
          ownership:
            operator: MSC
            registered_owner: ADRIANA OCEANWAY LTD
            technical_manager: MSC Shipmanagement
            ship_manager: MSC Shipmanagement
            group_beneficial_owner: MSC
          build_year: 1998
          deadweight: 18800
          dimensions:
            length: 216
            breadth: 26.7
          ship_status: In Service/Commission
          shipbuilder: HDW
          displacement: 0
          gross_tonnage: 25219
          country_of_build:
            country_code: DEU
            country_name: Germany
          port_of_registry: Monrovia
          classification_society: Det Norske Veritas
    vessel_characteristics_400:
      value:
        detail: The JWT token which was submitted has expired.
        documentation: ''
        field: ''
        request_id: 266ea41d-adf5-480b-af50-15b940c2b846
        resource_uri: /vessel-insights/v1/vessel-characteristics/12345
        status: 401
        timestamp: '2024-09-24T12:18:01Z'
        title: Expired JWT token
    vessel_characteristics_401:
      value:
        description: Example shared example
        type: object
        properties:
          id:
            type: string
        required:
          - id
    vessel_characteristics_403:
      value:
        description: Example shared example
        type: object
        properties:
          id:
            type: string
        required:
          - id
    vessel_characteristics_405:
      value:
        detail: The HTTP method which was used is not allowed on the requested resource.
        documentation: ''
        field: ''
        request_id: 266ea41d-adf5-480b-af50-15b940c2b846
        resource_uri: /vessel-insights/v1/vessel-characteristics/12345
        status: 405
        timestamp: '2024-09-24T12:18:01Z'
        title: Method Not Allowed
    vessel_characteristics_429:
      value:
        description: Example shared example
        type: object
        properties:
          id:
            type: string
        required:
          - id
    vessel_characteristics_500:
      value:
        meta:
          request_id: 004ab686-9a00-428c-b907-97812cf923ab
          request_timestamp: '2024-09-24T12:18:01Z'
        data:
          imo: '9169055'
          flag:
            name: Liberia
            country_code: LBR
            effective_date: '2017-11-12'
          mmsi: '636018321'
          name: MSC ADRIANA II
          type: Container (FC)
          draught: 19
          asset_id: ea2eac05-a542-4fc3-869a-d318057e3781
          callsign: D5PE9
          ownership:
            operator: MSC
            registered_owner: ADRIANA OCEANWAY LTD
            technical_manager: MSC Shipmanagement
            ship_manager: MSC Shipmanagement
            group_beneficial_owner: MSC
          build_year: 1998
          deadweight: 18800
          dimensions:
            length: 216
            breadth: 26.7
          ship_status: In Service/Commission
          shipbuilder: HDW
          displacement: 0
          gross_tonnage: 25219
          country_of_build:
            country_code: DEU
            country_name: Germany
          port_of_registry: Monrovia
          classification_society: Det Norske Veritas
    vessel_characteristics_404:
      value:
        detail: No record was found for the provided IMO number.
        documentation: ''
        field: ''
        request_id: 266ea41d-adf5-480b-af50-15b940c2b846
        resource_uri: /vessel-insights/v1/vessel-characteristics/12345
        status: 404
        timestamp: '2024-09-24T12:18:01Z'
        title: Resource Not Found
  schemas:
    VesselCharacteristicsResponseBody:
      type: object
      title: VesselCharacteristicsResponseBody
      description: Describes the full response for the Vessel Characteristics API.
      properties:
        meta:
          $ref: '#/components/schemas/ReponseMetaDataShort'
        data:
          $ref: '#/components/schemas/Vessel_Information'
      required:
        - meta
        - data
    ReponseMetaDataShort:
      type: object
      title: ReponseMetaDataShort
      description: Describes the metadata object returned in every response.
      properties:
        request_id:
          type: string
          description: The unique identifier of the request.
          format: uuid
          examples:
            - 266ea41d-adf5-480b-af50-15b940c2b846
        request_timestamp:
          type: string
          description: The date and time in UTC the request was made.
          format: date-time
          examples:
            - '2019-08-24T14:15:22Z'
      required:
        - request_id
        - request_timestamp
    Vessel_Information:
      type: object
      title: Vessel Information
      description: Describes the full set of vessel information fields at a single point in time.
      properties:
        asset_id:
          type: string
          description: Pole Star's unique asset identifier.
          format: uuid
        build_year:
          type:
            - integer
            - 'null'
          description: The year the vessel was built.
          format: int32
          examples:
            - 2010
        callsign:
          type:
            - string
            - 'null'
        classification_society:
          type:
            - string
            - 'null'
        country_of_build:
          type: object
          properties:
            country_name:
              type:
                - string
                - 'null'
            country_code:
              type:
                - string
                - 'null'
          required:
            - country_name
            - country_code
        deadweight:
          type:
            - integer
            - 'null'
          description: The vessel's deadweight.
          format: int32
          examples:
            - 148723
        dimensions:
          type: object
          description: The vessel's dimensions (length and width) in meters.
          properties:
            length:
              type:
                - number
                - 'null'
              description: The vessel's length in meters.
              format: float
              examples:
                - 366
            breadth:
              type:
                - number
                - 'null'
              description: The vessel's width in meters.
              format: float
              examples:
                - 48.2
          required:
            - length
            - breadth
        displacement:
          type:
            - number
            - 'null'
        draught:
          type:
            - number
            - 'null'
          format: float
          examples:
            - 19
        flag:
          type: object
          properties:
            name:
              type:
                - string
                - 'null'
              description: The country name of the flag registry the vessel is flagged to.
            country_code:
              type:
                - string
                - 'null'
              description: The three letter ISO country code of the country the vessel is flagged to.
            effective_date:
              type:
                - string
                - 'null'
              format: date
          required:
            - name
            - country_code
            - effective_date
          examples:
            - Denmark
        gross_tonnage:
          type:
            - number
            - 'null'
          description: Thje vessel's gross tonnage.
          format: float
          examples:
            - 141716
        imo:
          type: string
          description: The vessel's IMO number.
          examples:
            - 9456757
        mmsi:
          type: string
          description: The vessel's MMSI number.
          examples:
            - 219033000
        name:
          type: string
          description: The vessel's name.
          examples:
            - MAERSK EDINBURGH
        ownership:
          type: object
          properties:
            group_beneficial_owner:
              type:
                - string
                - 'null'
            operator:
              type:
                - string
                - 'null'
            registered_owner:
              type:
                - string
                - 'null'
            ship_manager:
              type:
                - string
                - 'null'
            technical_manager:
              type:
                - string
                - 'null'
          required:
            - group_beneficial_owner
            - operator
            - registered_owner
            - ship_manager
            - technical_manager
        port_of_registry:
          type:
            - string
            - 'null'
        shipbuilder:
          type:
            - string
            - 'null'
        ship_status:
          type:
            - string
            - 'null'
          description: The vessel's current status.
        type:
          type: string
          description: The vessel type of the vessel.
      required:
        - asset_id
        - build_year
        - callsign
        - classification_society
        - country_of_build
        - deadweight
        - dimensions
        - displacement
        - draught
        - flag
        - gross_tonnage
        - imo
        - mmsi
        - name
        - ownership
        - port_of_registry
        - shipbuilder
        - ship_status
        - type
    Error_Response:
      type: object
      title: Error Response
      description: Describes the general format of an HTTP error response.
      properties:
        detail:
          type: string
          description: Human-readable description of the error.
          examples:
            - The timestamp_end parameter was included in the request but no value was supplied.
        documentation:
          type: string
          format: uri
        field:
          type: string
          description: The parameter or field the error relates to (if known).
          examples:
            - timestamp_end
        request_id:
          type: string
          description: The unique identifier of this request.
          format: uuid
          examples:
            - 66ea41d-adf5-480b-af50-15b940c2b846
        resource_uri:
          type: string
          description: The requested resource's URI
          format: uri
          examples:
            - /v1/zone-traffic/266ea41d-adf5-480b-af50-15b940c2b846
        status:
          type: integer
          enum:
            - 400
            - 401
            - 403
            - 404
            - 405
            - 422
            - 429
            - 500
          description: The HTTP status code.
          examples:
            - '400'
        timestamp:
          type: string
          description: The date and time in UTC the error was generated.
          format: date-time
          examples:
            - '2019-08-24T14:15:22Z'
        title:
          type: string
          description: Human-readable summary of the problem.
          examples:
            - Timestamp End value not supplied
      required:
        - request_id
        - status
        - timestamp
x-internal: false
